/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.siap;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
/**
 *
 * @author joshu
 */
public class Horarios extends javax.swing.JFrame {
    
    private JDesktopPane desktopPane;
    Empresa empresa;
    /**
     * Creates new form Horarios
     */
    public Horarios(Empresa emp) {
        this.empresa = emp;
        desktopPane = new JDesktopPane();
        this.setContentPane(desktopPane);
        initComponents();
        
       
        
        cargarDatos();
    }
private void cargarDatos() {
    DefaultTableModel modelo = (DefaultTableModel) tblDatos.getModel();
    modelo.setRowCount(0);  // Limpiar el modelo de la tabla

    // Conectar a la base de datos SQLite
    Connection conn = null; // Declarar la conexión fuera del bloque try
    try {
        conn = empresa.getConexionBd(); // Obtener la conexión
        Statement stmt = conn.createStatement(); 
        ResultSet rs = stmt.executeQuery("SELECT horario, fecha, bus_id FROM Horarios");

        // Recorrer los resultados y agregarlos a la tabla
        while (rs.next()) {
            Object[] fila = new Object[3];  // Tres columnas: Horario, Fecha, Bus
            fila[0] = rs.getString("horario");
            fila[1] = rs.getString("fecha");
            fila[2] = rs.getInt("bus_id");
            modelo.addRow(fila);
        }
    } catch (Exception e) {
        e.printStackTrace();  // Imprimir error en consola para rastrear excepciones
    } finally {
        
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        botonAgregarHorario = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        botonnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Horario", "Fecha", "IdRuta"
            }
        ));
        jScrollPane2.setViewportView(tblDatos);

        jLabel1.setText("Gestor de Horarios");

        botonAgregarHorario.setText("Agregar");
        botonAgregarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarHorarioActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        botonnCerrar.setText("Cerrar");
        botonnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonAgregarHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
                .addContainerGap(320, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregarHorario)
                    .addComponent(jButton2))
                .addGap(154, 154, 154)
                .addComponent(botonnCerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarHorarioActionPerformed
                     AgregarHorario ventAgregarHorario = new AgregarHorario(empresa);
                    ventAgregarHorario.setVisible(true);
                    
           
        cargarDatos();
        
        
    }//GEN-LAST:event_botonAgregarHorarioActionPerformed

    private void botonnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonnCerrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            // TODO add your handling code here:
            VentEliminarHora ventEliminarHora = new VentEliminarHora(empresa);
         ventEliminarHora.setVisible(true);
                    
           
        cargarDatos();
       
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

        
              
        
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarHorario;
    private javax.swing.JButton botonnCerrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
