package com.mycompany.siap;


public class VentanaPrincipal extends javax.swing.JFrame {

    
    private Empresa empresa;
    
    public VentanaPrincipal(Empresa emp) 
    {
        empresa = emp;
        
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        realizarVenta = new javax.swing.JDialog();
        textoRutaRealizarV = new javax.swing.JTextField();
        confirmarIngresarRuta = new javax.swing.JButton();
        cancelarIngresarRuta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JOptionPane = new javax.swing.JOptionPane();
        Titulo1 = new javax.swing.JLabel();
        SubTitulo1 = new javax.swing.JLabel();
        botonGestionRutas = new javax.swing.JButton();
        botonRealizarVenta = new javax.swing.JButton();
        botonGestionarBuses = new javax.swing.JButton();
        botonMenuListar = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        botonGestionarHorariosS = new javax.swing.JButton();

        realizarVenta.setName("Realizar Venta"); // NOI18N

        confirmarIngresarRuta.setText("Confirmar");
        confirmarIngresarRuta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmarIngresarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarIngresarRutaActionPerformed(evt);
            }
        });

        cancelarIngresarRuta.setText("Cancelar");
        cancelarIngresarRuta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelarIngresarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarIngresarRutaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel3.setText("Ingrese la id de la ruta  ");

        javax.swing.GroupLayout realizarVentaLayout = new javax.swing.GroupLayout(realizarVenta.getContentPane());
        realizarVenta.getContentPane().setLayout(realizarVentaLayout);
        realizarVentaLayout.setHorizontalGroup(
            realizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(realizarVentaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(realizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(realizarVentaLayout.createSequentialGroup()
                        .addComponent(cancelarIngresarRuta)
                        .addGap(207, 207, 207)
                        .addComponent(confirmarIngresarRuta))
                    .addGroup(realizarVentaLayout.createSequentialGroup()
                        .addComponent(textoRutaRealizarV, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addComponent(jLabel3))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        realizarVentaLayout.setVerticalGroup(
            realizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(realizarVentaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(textoRutaRealizarV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(realizarVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmarIngresarRuta)
                    .addComponent(cancelarIngresarRuta))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de gestion de buses");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setName("VentanaApp"); // NOI18N

        Titulo1.setBackground(new java.awt.Color(255, 255, 255));
        Titulo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo1.setText("Bienvenido Al Sistema De Gestion de buses");
        Titulo1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Titulo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        SubTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SubTitulo1.setText("Haga Click en la opcion que desea");
        SubTitulo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        botonGestionRutas.setText("Gestionar Rutas");
        botonGestionRutas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGestionRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionRutasActionPerformed(evt);
            }
        });

        botonRealizarVenta.setText("Realizar Venta");
        botonRealizarVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRealizarVenta.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        botonRealizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRealizarVentaActionPerformed(evt);
            }
        });

        botonGestionarBuses.setText("Gestionar Buses");
        botonGestionarBuses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGestionarBuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionarBusesActionPerformed(evt);
            }
        });

        botonMenuListar.setText("Menu Listar");
        botonMenuListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMenuListar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonMenuListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuListarActionPerformed(evt);
            }
        });

        botonCerrar.setText("Cerrar");
        botonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        jButton1.setText("Realizar Reportes");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botonGestionarHorariosS.setText("Gestionar Horarios");
        botonGestionarHorariosS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionarHorariosSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(SubTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addGap(297, 297, 297))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonCerrar)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGestionRutas)
                    .addComponent(jButton1)
                    .addComponent(botonGestionarBuses))
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonGestionarHorariosS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRealizarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(botonMenuListar, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(Titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGestionRutas)
                    .addComponent(botonRealizarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGestionarBuses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonMenuListar))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(botonGestionarHorariosS))
                .addGap(150, 150, 150)
                .addComponent(botonCerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGestionRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionRutasActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
        {
                public void run()
                {
                    VentanaRuta vent = new VentanaRuta (empresa);
                    
                    vent.setVisible(true);
                }
                    
            });
    }//GEN-LAST:event_botonGestionRutasActionPerformed

    private void botonRealizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRealizarVentaActionPerformed
        realizarVenta.setSize(600, 400);
        realizarVenta.setLocationRelativeTo(null);
        
        
        realizarVenta.setVisible(true);
        

                    
    }//GEN-LAST:event_botonRealizarVentaActionPerformed

    private void botonGestionarBusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarBusesActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
        {
                public void run()
                {
                    VentanaBuses vent = new VentanaBuses (empresa);
                    
                    vent.setVisible(true);
                }
                    
            });
         
    }//GEN-LAST:event_botonGestionarBusesActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        System.exit(0);
       
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void botonMenuListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuListarActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable()
        {
                public void run()
                {
                    VentanaListar vent = new VentanaListar (empresa);
                    
                    vent.setVisible(true);
                }
                    
            });
       
    }//GEN-LAST:event_botonMenuListarActionPerformed

    private void confirmarIngresarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarIngresarRutaActionPerformed

        String t = textoRutaRealizarV.getText();

        try {
            // Intentar convertir el texto a un número entero
            int id = Integer.parseInt(t);

            // Usar EventQueue para crear y mostrar el JDialog
            java.awt.EventQueue.invokeLater(new Runnable() 
            {
                public void run() 
                {
                    VentanaSelecccionarHorario vent = new VentanaSelecccionarHorario(empresa, id);
                    vent.setVisible(true);
                }
            });

            // Cerrar la ventana actual
            realizarVenta.dispose();

        } catch (NumberFormatException e) 
        {
            // Manejo de excepción si el texto no puede ser convertido a entero
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido para la ruta.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Manejo de cualquier otra excepción
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_confirmarIngresarRutaActionPerformed

    private void cancelarIngresarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarIngresarRutaActionPerformed
        realizarVenta.dispose();
    }//GEN-LAST:event_cancelarIngresarRutaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() 
            {
                public void run() 
                {
                    VentReportes vent = new VentReportes(empresa);
                    vent.setVisible(true);
                }
            });

    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonGestionarHorariosSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionarHorariosSActionPerformed
                java.awt.EventQueue.invokeLater(new Runnable()
        {
                public void run()
                {
                   Horarios ventanaHorarios= new Horarios(empresa);
                   ventanaHorarios.setVisible(true);
                   ventanaHorarios.setLocationRelativeTo(null);
                }
                    
            });
    }//GEN-LAST:event_botonGestionarHorariosSActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane JOptionPane;
    private javax.swing.JLabel SubTitulo1;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonGestionRutas;
    private javax.swing.JButton botonGestionarBuses;
    private javax.swing.JButton botonGestionarHorariosS;
    private javax.swing.JButton botonMenuListar;
    private javax.swing.JButton botonRealizarVenta;
    private javax.swing.JButton cancelarIngresarRuta;
    private javax.swing.JButton confirmarIngresarRuta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JDialog realizarVenta;
    private javax.swing.JTextField textoRutaRealizarV;
    // End of variables declaration//GEN-END:variables
    
}
